apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-app
  labels:
    app: brain-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task-app
  template:
    metadata:
      labels:
        app: brain-task-app
    spec:
      containers:
        - name: brain-task-app
          image: 235391889675.dkr.ecr.ap-south-1.amazonaws.com/aws-brain-task-app-docker:latest
          ports:
            - containerPort: 80

